#!/bin/sh

CONTAINER_NAME="fedora"

echo "Creating fedora container"
toolbox --assumeyes create "$CONTAINER_NAME"

__run() {
    toolbox run --container "$CONTAINER_NAME" "$@"
}

echo "Enabling copr repositories"
__run sudo dnf -y copr enable petersen/haskell-language-server
__run sudo dnf -y copr enable yorickpeterse/lua-language-server

echo "Installing development software"
__run sudo dnf -y install neovim \
    fd-find \
    ripgrep \
    cmake clang-tools-extra gcc-c++ \
    nodejs-bash-language-server \
    shellcheck \
    haskell-language-server \
    lua-language-server \
    clippy rust-analyzer \
    rustfmt \
    gh \
    yt-dlp \
    zsh

echo "Done!"
