#!/bin/sh

echo "Creating fedora container"
toolbox -y create

__run() {
    toolbox run "$@"
}

echo "Enabling copr repositories"
__run sudo dnf -y copr enable petersen/haskell-language-server
__run sudo dnf -y copr enable yorickpeterse/lua-language-server

echo "Installing development software"
__run sudo dnf -y install neovim \
    fd-find \
    ripgrep \
    cmake clang-tools-extra gcc-c++ \
    checksec openssl \
    nodejs-bash-language-server \
    shellcheck \
    haskell-language-server \
    lua-language-server \
    clippy rust-analyzer \
    rustfmt \
    gh \
    yt-dlp

echo "Linking xdg-open to flatpak-xdg-open"
__run sudo dnf -y remove xdg-utils
__run sudo dnf -y install flatpak-xdg-utils
__run sudo ln -s /usr/bin/flatpak-xdg-open /usr/bin/xdg-open

echo "Done!"
