FROM registry.fedoraproject.org/fedora-toolbox:39

# Add image label
ARG NAME=dev-toolbox
ARG VERSION=39
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Image for creating Fedora Toolbx containers"

# Add COPR repositories
# RUN dnf --assumeyes copr enable petersen/haskell-language-server
# RUN dnf --assumeyes copr enable yorickpeterse/lua-language-server

# Install extra packages
COPY extra-packages /
RUN dnf --assumeyes install $(<extra-packages)
RUN rm /extra-packages

# Add nvim bootstrapping file
# RUN mkdir -p /etc/xdg/nvim/
# COPY sysinit.vim /etc/xdg/nvim/

# Fix xdg-open using symlink
# RUN dnf --assumeyes remove xdg-utils
# RUN dnf --assumeyes install flatpak-xdg-utils
# RUN ln --symbolic /usr/bin/flatpak-xdg-open /usr/bin/xdg-open

# Clean dnf cache
RUN dnf clean all
