FROM registry.fedoraproject.org/fedora-toolbox:40

# Add image label
ARG NAME=dev-toolbox
ARG VERSION=40
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Image for creating Fedora Toolbx containers"

# Enable copr repositories
RUN dnf --assumeyes copr enable petersen/haskell-language-server
RUN dnf --assumeyes copr enable yorickpeterse/lua-language-server

# Install extra packages
COPY extra-packages /
RUN dnf --assumeyes install $(<extra-packages)
RUN rm /extra-packages

# Clean dnf cache
RUN dnf clean all

# Install slint tools
COPY slint-tools /
RUN /slint-tools
RUN rm /slint-tools

# Add bubblewrap sandbox
COPY sandbox /usr/local/bin/
RUN echo '[ -z "$SANDBOX" ] && exec "/usr/local/bin/sandbox"' >> /etc/profile

# Fix konsole version (toolbx 0.0.99.5) 
COPY konsole-version.sh /etc/profile.d/
