#!/bin/sh

SANDBOX="$(date +%T)"
export SANDBOX

WAYLAND="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"

. "/run/.containerenv"
CONTAINER_DIR="$HOME/Toolbox/$name"
mkdir --parents "$CONTAINER_DIR"
cp --no-clobber --recursive "/etc/skel/." "$CONTAINER_DIR" 2>/dev/null

bwrap \
    --ro-bind /bin /bin \
    --ro-bind /etc /etc \
    --ro-bind /lib /lib \
    --ro-bind /lib64 /lib64 \
    --ro-bind /opt /opt \
    --ro-bind /sbin /sbin \
    --ro-bind /usr /usr \
    --ro-bind /sys /sys \
    --ro-bind "$WAYLAND" "$WAYLAND" \
    --ro-bind "/run/.containerenv" "/run/.containerenv" \
    --ro-bind "/run/.toolboxenv" "/run/.toolboxenv" \
    --ro-bind "/run/systemd/resolve" "/run/systemd/resolve" \
    --bind "$CONTAINER_DIR" "$HOME" \
    --chdir "$HOME" \
    --dev /dev \
    --proc /proc \
    --tmpfs /tmp \
    --dev-bind /dev/dri /dev/dri \
    /usr/bin/bash
