#!/bin/sh

WAYLAND="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"
X11_UNIX="/tmp/.X11-unix"

ISOLATED_HOME="$HOME/.var/box"
mkdir --parents "$ISOLATED_HOME"
cp --recursive --update=none "/etc/skel/." "$ISOLATED_HOME"

bwrap \
    --ro-bind /bin /bin \
    --ro-bind /etc /etc \
    --ro-bind /lib /lib \
    --ro-bind /lib64 /lib64 \
    --ro-bind /opt /opt \
    --ro-bind /sbin /sbin \
    --ro-bind /usr /usr \
    --ro-bind /sys /sys \
    --ro-bind "$WAYLAND" "$WAYLAND" \
    --ro-bind "$X11_UNIX" "$X11_UNIX" \
    --ro-bind "$XAUTHORITY" "$XAUTHORITY" \
    --ro-bind "/run/.containerenv" "/run/.containerenv" \
    --ro-bind "/run/.toolboxenv" "/run/.toolboxenv" \
    --ro-bind "/run/systemd/resolve" "/run/systemd/resolve" \
    --bind "$ISOLATED_HOME" "$HOME" \
    --chdir "$HOME" \
    --dev /dev \
    --proc /proc \
    --tmpfs /tmp \
    --tmpfs "/etc/ssh/ssh_config.d" \
    --dev-bind "/dev/dri" "/dev/dri" \
    /usr/bin/bash
